version: '3.8'

services:
  data:
    container_name: data
    image: python:3.11.2
    ports:
      - "8080:8080"
    volumes:
      - /home/kamilo/Documentos/analisis:/app
    working_dir: /app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8080 --reload"
